# Generated by Django 5.2.1 on 2025-05-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_locations_murderstats_suspectlist_delete_burgermenu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='MurderStats',
            new_name='MurderStat',
        ),
    ]
