# Generated by Django 5.2.1 on 2025-05-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_locations_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('years_experience', models.IntegerField()),
                ('birth_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='murderstat',
            name='murderNotice',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='suspectlist',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_text', models.TextField()),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detective')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suspectlist')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suspectlist')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trait')),
            ],
        ),
    ]
