# Generated by Django 5.2.1 on 2025-05-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detective_trait_alter_murderstat_murdernotice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='murderstat',
            name='murderLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
